### ISSUE TITLE
some error

### ISSUE THREAD

**Issue by zc994646659** [JaGeo/LobsterPy#10]
Hi,
when I run lobsterpy automatic-plot ,it reported as followed,
/data/software/anaconda/2020.07/envs/lobsterpy/lib/python3.8/site-packages/pymatgen/electronic_structure/cohp.py:164: UserWarning: This method has not been tested on many examples. Check the parameter limit, pls!
  warnings.warn("This method has not been tested on many examples. Check the parameter limit, pls!")
and it did not generate any results.How can solve the problem.thanks
zhou chao

**Comment by JaGeo** [comment]
This is a warning to carefully check your results as the program and pymatgen implementations are new. It can usually be ignored.

Does really nothing happen afterwards? Depending on system size it may take a while. 🙂 

Otherwise, it would help if you provided the files for which this happens.

JG

**Comment by JaGeo** [comment]
I hope this solved the issue. I am closing the issue for now.
