### ISSUE TITLE
Orbital-resolved automatic analysis

### ISSUE THREAD

**Issue by JaGeo** [JaGeo/LobsterPy#113]
**Is your feature request related to a problem? Please describe.**
I would like to implement an automatic analysis including orbital-resolved interactions. I will add this as an additional option so that people can also skip the orbital-resolved analysis.

I hope to accomplish this in the next 4 weeks.

**Comment by naik-aakash** [comment]
Can we close this now?

**Comment by JaGeo** [comment]
Closed by #132
