### ISSUE TITLE
Code-agnostic automatic analyisis

### ISSUE THREAD

**Issue by JaGeo** [JaGeo/LobsterPy#124]
It would be good to get our automatic analysis working for QE and Abinit outputs as well.

@davSchnieders, it would be great if you could provide a sample output. We could then make automatic analysis work for QE as well.

**Comment by davSchnieders** [comment]
No problem, I will attach a minimalistic example. Please don't mind the low accuracy calculation, it is fast, not accurate.
[sample_input.tar.gz](https://github.com/JaGeo/LobsterPy/files/11965172/sample_input.tar.gz)

**Comment by davSchnieders** [comment]
Which information is actually needed by LobsterPy? Maybe there is a way to provide the necessary data with LOBSTER directly in a future release, so there is no need to parse the various types of electronic-structure input formats.

**Comment by JaGeo** [comment]
I will let you know! I think it is mostly the structural information.

**Comment by davSchnieders** [comment]
We could print a "POSCAR.lobster" file containing the structure (as the POSCAR format can be read by almost every code in the community). This would then directly allow to use any LOBSTER calculation (also those based on QE or ABINIT) with LobsterPy, as long as only the structure is needed as additional info.

**Comment by JaGeo** [comment]
Yes, this would be awesome!

**Comment by JaGeo** [comment]
One other thing: fatband plots required many vasp specific files, if I remembered correctly.

**Comment by JaGeo** [comment]
Can be closed as the new Lobster release will fix this issue with a POSCAR.lobster file.

**Comment by Quantumiceage** [comment]
Hello, can I use lobsterpy to plot the k-dependent COHP generated by lobster?

**Comment by JaGeo** [comment]
Not yet. The lobster output files have been extremely large and this limited the integration.
