### ISSUE TITLE
"lobsterpy automatic-plot-ia --label-resolved" stopped working

### ISSUE THREAD

**Issue by JaGeo** [JaGeo/LobsterPy#140]
**Describe the bug**
`lobsterpy automatic-plot-ia --label-resolved`
@naik-aakash , it raises an error and I am not sure where it comes from.

**Comment by naik-aakash** [comment]
Can you post the error please ? For my local repo with current master branch it works

**Comment by JaGeo** [comment]
I ran it in "TestData/NaSbF6"

**Comment by naik-aakash** [comment]
This is strange. It works fine for me without error. I just checked for both `cation-anion` and`all` bonds mode

**Comment by naik-aakash** [comment]
> I ran it in "TestData/NaSbF6"
> 
> and get `AttributeError: 'tuple' object has no attribute 'atoms'`

Seems it could probably stem from pymatgen ?

**Comment by JaGeo** [comment]
I will make a fresh environment and then see.

**Comment by JaGeo** [comment]
Now, with the latest pymatgen, it works. I think a fix would be to require a newer pymatgen version.

**Comment by JaGeo** [comment]
But we need a test to make sure it doesn't break again. ;)

**Comment by naik-aakash** [comment]
> But we need a test to make sure it doesn't break again. ;)

I do not know tbh, what kind of test will need to be written for such a case.  Any ideas ?

**Comment by JaGeo** [comment]
Do we test the label-resolved plotter? You could simply test if you can execute the command with the testfolder I mentioned above.

**Comment by naik-aakash** [comment]
> Do we test the label-resolved plotter? You could simply test if you can execute the command with the testfolder I mentioned above.

Yes, we do that test. Just not in CLI, but normal Python interface. If it does not work, it will get caught in there if something is wrong with pymatgen version

**Comment by JaGeo** [comment]
I used a fresh environment and installed LobsterPy. Then an older pymatgen version was installed and it failed. Our test should then be failing as well, shouldn't it?

**Comment by naik-aakash** [comment]
> I used a fresh environment and installed LobsterPy. Then an older pymatgen version was installed and it failed. Our test should then be failing as well, shouldn't it?

Yes it should fail definitely. Will see what's happening

**Comment by JaGeo** [comment]
I have updated the pymatgen version number for now and we have to make sure we keep this updated in the future.
