### ISSUE TITLE
"get_anion_types is deprecated; use anion_types in pymatgen.io.lobster.lobsterenv instead."

### ISSUE THREAD

**Issue by JaGeo** [JaGeo/LobsterPy#173]
We deprecated "get_anion_types" in pymatgen. We should therefore switch to the new command.

**Comment by naik-aakash** [comment]
> We deprecated "get_anion_types" in pymatgen. We should therefore, switch to the new command.

I was thinking of making this change. Nice to have a track now 😄 . Thanks!
