### ISSUE TITLE
calc_quality_summary : dict keys needs to follow snakecase and some renaming

### ISSUE THREAD

**Issue by naik-aakash** [JaGeo/LobsterPy#175]
Currently not all keys do not have snake_case convention: got over looked in paper

As lot of things are changed compared to our publication, maybe better to fix them now itself.

Also for example some keys like : charges and bandoverlaps could be renamed to be bit more descriptive as our larger schema already same keys with different data in it on top level 

What do you think @JaGeo ?

**Comment by JaGeo** [comment]
Yeah. Just fix it. We will add additional documentation for it here
