### ISSUE TITLE
Add automatic analysis for COBIs, COOPs

### ISSUE THREAD

**Issue by JaGeo** [JaGeo/LobsterPy#21]
This will allow to also automatially plot COOPs and COBIs but would require additional changes in pymatgen first.

**Comment by naik-aakash** [comment]
- [ ] Made first changes in pymatgen for this functionality.  

## Query

-  Do we add modules for seperate analysis or just extend the cohp module to handle cobi/coop ? 

Extending modules will avoid code repetition as major chunk of code will still be same. Then we would probably need to restructure or rename modules. Let me know your thoughts.

**No urgency to respond quickly. Have other things to work on till then** 😃

## Todo

- [ ]  Add modules corresponding to coop/cobi analysis and description

**Comment by JaGeo** [comment]
I think we should avoid conde repetition. I am not really sure if we need to restructure that much? How about adding "is_cobi", "is_coop" as a flag and then see how this works out?

For the graphs, the fix might include some more if clauses but should also be doable. 

With regard to priorities: I think this is something we could do before we submit a paper on lobsterpy itself. I think I will also extend the time frame for this submission (mid 2023)

**Comment by JaGeo** [comment]
Done in #128
