### ISSUE TITLE
pip installation fails

### ISSUE THREAD

**Issue by srmnitc** [JaGeo/LobsterPy#221]
**Describe the bug**
This is part of the review over at https://github.com/openjournals/joss-reviews/issues/6286. I tried to install using pip in a clean conda environment, and the installation fails with the attached message

**To Reproduce**
1. create new conda env
2. install pip
3. run `pip install lobsterpy`

**Expected behavior**
Should install the package

**Screenshots**
```

  Building wheel for spglib (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Building wheel for spglib (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [37 lines of output]
      /tmp/pip-build-env-esh8lx6s/normal/lib/python3.12/site-packages/setuptools_scm/git.py:308: UserWarning: git archive did not support describe output
        warnings.warn("git archive did not support describe output")
      /tmp/pip-build-env-esh8lx6s/normal/lib/python3.12/site-packages/setuptools_scm/git.py:327: UserWarning: unprocessed git archival found (no export subst applied)
        warnings.warn("unprocessed git archival found (no export subst applied)")
      *** scikit-build-core 0.8.0 using CMake 3.16.3 (wheel)
      *** Configuring CMake...
      2024-02-07 09:51:59,847 - scikit_build_core - WARNING - libdir/ldlibrary: /home/menon/miniconda3/envs/lobsterpy/lib/libpython3.12.a is not a real file!
      2024-02-07 09:51:59,847 - scikit_build_core - WARNING - Can't find a Python library, got libdir=/home/menon/miniconda3/envs/lobsterpy/lib, ldlibrary=libpython3.12.a, multiarch=x86_64-linux-gnu, masd=None
      loading initial cache file /tmp/tmpgrjd0cxd/build/CMakeInit.txt
      CMake Error: Error processing file: COMMAND_ERROR_IS_FATAL
      CMake Error at cmake/DynamicVersion.cmake:270 (file):
        file failed to open for reading (No such file or directory):

          /tmp/tmpgrjd0cxd/build/tmp/.DynamicVersion.json
      Call Stack (most recent call first):
        CMakeLists.txt:14 (dynamic_version)


      CMake Warning at CMakeLists.txt:18 (project):
        VERSION keyword not followed by a value or was followed by a value that
        expanded to nothing.


      -- The C compiler identification is GNU 9.3.0
      -- Check for working C compiler: /usr/bin/cc
      -- Check for working C compiler: /usr/bin/cc -- works
      -- Detecting C compiler ABI info
      -- Detecting C compiler ABI info - done
      -- Detecting C compile features
      -- Detecting C compile features - done
      -- Spglib:: Build type: Release
      -- Spglib:: Version
      -- Found Python3: /home/menon/miniconda3/envs/lobsterpy/bin/python3.12 (found version "3.12.1") found components: Interpreter Development.Module NumPy
      -- Configuring incomplete, errors occurred!
      See also "/tmp/tmpgrjd0cxd/build/CMakeFiles/CMakeOutput.log".

      *** CMake configuration failed
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for spglib
  Building wheel for future (setup.py) ... done
  Created wheel for future: filename=future-0.18.3-py3-none-any.whl size=492024 sha256=5d5097157e5f196a515ad1e810b8ad8139b38c60699d49591587c34fa5e1a2ca
  Stored in directory: /home/menon/.cache/pip/wheels/f1/54/27/4e5cb4bd05116c097877e85a206a2e08d301aaa9b7af719909
Successfully built pymatgen typing future
Failed to build spglib
ERROR: Could not build wheels for spglib, which is required to install pyproject.toml-based projects
```

**Desktop (please complete the following information):**
 - WSL with Ubuntu 20

**Comment by JaGeo** [comment]
Thanks. We will check and resolve. (@naik-aakash ).

**Comment by naik-aakash** [comment]
Hi @srmnitc , thank you for reporting this. 

Can you please check if the issue still persist if using any python version <3.12 ? For example 3.11 or so?

Seems the problem is not specific to lobsterpy but originates from pymatgen dependencies. And using python 3.12, I also encounter the same issue, but with python 3.11, it does not occur. (Seems many packages are not yet fully adapted to support latest python version)

**Comment by JaGeo** [comment]
@naik-aakash can we be somehow clearer in which Python versions we support?

**Comment by naik-aakash** [comment]
> @naik-aakash can we be somehow clearer in which Python versions we support?

We already have this mentioned which python versions work in our pyproject.toml https://github.com/JaGeo/LobsterPy/blob/8e777b85a71f8e128ae141449db456a25ec94f3f/pyproject.toml#L20 and also visible on pypi https://pypi.org/project/lobsterpy/.

I can think of adding only hard coded limit here to avoid such issues in future> https://github.com/JaGeo/LobsterPy/blob/8e777b85a71f8e128ae141449db456a25ec94f3f/pyproject.toml#L29

**Comment by srmnitc** [comment]
Thanks! I was indeed using python 3.12. The installation works fine for 3.11. I can see now that the versions are also clearly defined, however, I just did a pip install, and it did not complain about the python version, but rather crashed. Maybe it is better to specify this. That being said, feel free to close this issue. Thanks for the quick resolution.

**Comment by JaGeo** [comment]
We might want to set a maximum Python version, though. Thanks! 

@naik-aakash Could you check if works?
