### ISSUE TITLE
Information on how to run the tests

### ISSUE THREAD

**Issue by srmnitc** [JaGeo/LobsterPy#223]
**Is your feature request related to a problem? Please describe.**
This is part of the review over at https://github.com/openjournals/joss-reviews/issues/6286. The project seems to have automated tests, but I could not find instructions on how a user can run the tests. This would allow me to check off the 'Automated Tests' in the review.

**Describe the solution you'd like**
Add a documentation on how to run tests in both README and documentation page

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by JaGeo** [comment]
Thank you, @srmnitc . Could you check if this description works: https://jageo.github.io/LobsterPy/dev/dev_installation.html ? 

If not, please let us know and we are happy to help.

**Comment by JaGeo** [comment]
Meanwhile, @naik-aakash and I will be thinking about how to make this documentation part more discoverable.

**Comment by srmnitc** [comment]
Perfect @JaGeo! That works, I was able to run the tests. Once again, a link to the dev docs would be nice, but everything works very well. Feel free to close the issue.

**Comment by JaGeo** [comment]
Could you please download the latest main branch, upgrade the pymatgen version and check if the error persists? I assume it is a related to a very recent upgrade in pymatgen.

**Comment by naik-aakash** [comment]
Hi @srmnitc , this is result of recent change in pymatgen. We relased a new version of LobsterPy yesterday that address this issue. Try upgrading the lobsterpy.

**Comment by srmnitc** [comment]
> Could you please download the latest main branch, upgrade the pymatgen version (`pip install --upgrade pymatgen`) and check if the error persists? I assume it is a related to a very recent upgrade in pymatgen. @naik-aakash fixed that error yesterday here on the main branch.

This solution worked, thanks.
