### ISSUE TITLE
Suggestions for JOSS paper

### ISSUE THREAD

**Issue by srmnitc** [JaGeo/LobsterPy#225]
Here are some suggestions for the JOSS paper:

- citation for LOBSTER
- are there any tools similar to lobsterpy in the community?

**Comment by JaGeo** [comment]
@srmnitc , @naik-aakash and I have addressed your comments in #226 . Are you fine with the changes?

**Comment by srmnitc** [comment]
@JaGeo Thanks, everything looks good to me!

**Comment by JaGeo** [comment]
Great, @srmnitc. We will merge then and close this issue (cc @RMeli )
