### ISSUE TITLE
`lobsterpy plot-automatic-ia -orbplot` does not work

### ISSUE THREAD

**Issue by JaGeo** [JaGeo/LobsterPy#252]
Currently, using `lobsterpy plot-automatic-ia -orbplot` is not successful. Lobsterpy warns me instead with "Please set orbital_resolved to True when instantiating Analysis object, to get this data" and returns the non-orbital-resolved data.

**Comment by naik-aakash** [comment]
Hi @JaGeo, just checked it is intended to work together with `-orbresol`  https://github.com/JaGeo/LobsterPy/blob/e49eef96ab6b87fdb74bff87ab88a7dc292cfc8c/lobsterpy/cli.py#L461

**Comment by JaGeo** [comment]
But that is not documented.

**Comment by naik-aakash** [comment]
The help for orbplot also shows this. This I have added to not turn on by default so users have option to enable or disable.


It is also in the documentation it is visible https://jageo.github.io/LobsterPy/reference/cli_subcommands/plotautoia.html

**Comment by JaGeo** [comment]
I did not find it and gave up.

**Comment by naik-aakash** [comment]
Will add a fix

**Comment by JaGeo** [comment]
Thanks. We could add a meme of a PI coming to the lab and letting all experiments explode here 😅
