### ISSUE TITLE
Developers installation out of date

### ISSUE THREAD

**Issue by JaGeo** [JaGeo/LobsterPy#295]
The packages in the pyproject.toml do not agree with what we install on the repo. This should be fixed.

**Comment by naik-aakash** [comment]
Hi @JaGeo, It was flake8, right? Now it everything seems fine. Or any specific package you meant?

**Comment by JaGeo** [comment]
Can you just document rhe developers installation in the readme?

**Comment by naik-aakash** [comment]
Hi @JaGeo , Sorry am not sure I understand what you mean. The associated link is already there in the readme for the developers installation in the readme [here](https://github.com/JaGeo/LobsterPy/blob/55d8d2e119aa1147166994d57fbdbe10931cc748/README.md?plain=1#L82)

**Comment by JaGeo** [comment]
@naik-aakash I think the dev installation should be moved to the installation part of the readme. I feel this is the more natural place. I had actually overlooked the installation link there.

**Comment by naik-aakash** [comment]
> @naik-aakash I think the dev installation should be moved to the installation part of the readme. I feel this is the more natural place. I had actually overlooked the installation link there.

Sure. I will raise a PR with the changes soon

**Comment by naik-aakash** [comment]
# Todo

- [ ] Make github CI workflow consistent with dev installation (remove redundant pytestify )
- [ ] Restructure readme (move dev installation section below installation)

**Comment by JaGeo** [comment]
You can pin numpy as well
