### ISSUE TITLE
Fractional occupancies.

### ISSUE THREAD

**Issue by hongyi-zhao** [JaGeo/LobsterPy#308]
[For some elements](https://www.vasp.at/wiki/index.php/Available_pseudopotentials#potpaw.54), fractional occupancies of the atomic reference configuration are used when generating the pseudopotentials, as shown below:
 
![image](https://github.com/JaGeo/LobsterPy/assets/11155854/0ea820a7-b2a7-4a0b-bf63-ad7e7676cc94)

But this is not reflected in the [lobster_basis](https://github.com/materialsproject/pymatgen/tree/master/src/pymatgen/io/lobster/lobster_basis) used by this package. Is this reasonable?

See [here](https://www.vasp.at/forum/viewtopic.php?p=26860#p26860) and [here](https://github.com/JaGeo/LobsterPy/issues/306#issuecomment-2191604509) for the related discussions.

Regards,
Zhao

**Comment by JaGeo** [comment]
The min file does not have them, the max file does. This, these orbitals are tested.

I think we had an updated version of the scripts at some point or we manually removed these orbitals from min for Be and Ba. They lad to poor projections for semicondictors but are needed for metals.

**Comment by JaGeo** [comment]
Ah, one more thing: there is an issue for Ba. You might want to check out our database paper. We explain it there.

**Comment by hongyi-zhao** [comment]
> The min file does not have them, the max file does.

However, the form of fractional occupancies used on the VASP wiki does not appear in the following document:

https://github.com/materialsproject/pymatgen/blob/master/src/pymatgen/io/lobster/lobster_basis/BASIS_PBE_54_max.yaml

> You might want to check out our database paper.

Do you mean this one: https://doi.org/10.1002/cplu.202200123?

**Comment by JaGeo** [comment]
> > The min file does not have them, the max file does.
> 
> However, the form of fractional occupancies used on the VASP wiki does not appear in the following document:
> 
> https://github.com/materialsproject/pymatgen/blob/master/src/pymatgen/io/lobster/lobster_basis/BASIS_PBE_54_max.yaml
> 
> > You might want to check out our database paper.


It depends which orbitals arw available in Lobster and Lobster can only project into the whole orbtial. There is no way to reflect this in the files other than adding the whole orbital to the max file.

**Comment by JaGeo** [comment]
This one: https://www.nature.com/articles/s41597-023-02477-5

**Comment by JaGeo** [comment]
Will close this as we cannot directly enforce the occupancy in Lobster
