### ISSUE TITLE
What about add PBE_64 into the _valid_potcars list of the LobsterSet function defined in pymatgen?

### ISSUE THREAD

**Issue by hongyi-zhao** [JaGeo/LobsterPy#317]
Hi there,

Considering that [potpaw.64](https://www.vasp.at/wiki/index.php/Available_pseudopotentials#potpaw.64_(latest,_recommended)) is the latest and recommended pseudopotentials by vasp team, and there are so many overlaps shared by potpaw.64 and potpaw.54, I would like to know if we can safely add PBE_64 into [the _valid_potcars](https://github.com/materialsproject/pymatgen/blob/5256fce19f7366d33fd5b062bd41cc5cb713505f/src/pymatgen/io/vasp/sets.py#L2682) list of the LobsterSet function defined in pymatgen for the moment to let PBE_64 use the already made [lobster basis](https://github.com/materialsproject/pymatgen/tree/master/src/pymatgen/io/lobster/lobster_basis) if available.

See the related discussions below:
https://github.com/materialsproject/pymatgen/issues/3956
https://github.com/materialsproject/pymatgen/issues/3893
https://github.com/JaGeo/LobsterPy/issues/304#issuecomment-2187919611
https://github.com/materialsproject/pymatgen/discussions/3488

Regards,
Zhao

**Comment by JaGeo** [comment]
I think you would need to update the basis functions files. Currently, I am only using 54 POTCAR information, to determine the right basis functions.

**Comment by hongyi-zhao** [comment]
What I mean is, for the potcar files that are the same in POTPAW.64 and POTPAW.54, in this case, do I also need to update the basis function files? If not, then there shouldn't be any issue with using the existing basis function files directly in this case, right?

**Comment by hongyi-zhao** [comment]
So, I would like to make a PR to add PBE_64 into the _valid_potcars list of the LobsterSet function defined in pymatgen. Do you agree? If in the future we have generated the basis function files for the updated and newly added potcars in [potpaw.64](https://www.vasp.at/wiki/index.php/Available_pseudopotentials#potpaw.64_(latest,_recommended)), then implement the corresponding code adjustment and enhancement.

**Comment by JaGeo** [comment]
Yeah. Please go ahead but please raise a warning that the basis functions have been generated with the 54 potcars

**Comment by hongyi-zhao** [comment]
Done, see https://github.com/materialsproject/pymatgen/pull/3967.
