### ISSUE TITLE
The inappropriate code snippet appeared in the `Command line interface` tutorial.

### ISSUE THREAD

**Issue by hongyi-zhao** [JaGeo/LobsterPy#318]
I noticed the following code snippet in the [`Command line interface` tutorial](https://jageo.github.io/LobsterPy/tutorial/commandlineinterface.html#analyze-the-lobster-outputs-with-automation):

```python
import os
os.chdir('Basis_0/') # Navigate to directory containing the files of lobster runs
```

What makes me feel strange is that this part of the tutorial is all about explaining the command line interface. Why would it suddenly provide the above Python code? It doesn't have any direct correlation with the operations in this context.

Regards,
Zhao

**Comment by naik-aakash** [comment]
Thanks for notifying us. Agreed, this is leftover of previous version of documentation and has been removed now.
