### ISSUE TITLE
Calc quality analysis needs to be updated

### ISSUE THREAD

**Issue by naik-aakash** [JaGeo/LobsterPy#325]
After merging this https://github.com/materialsproject/pymatgen/pull/3946 PR and a newer pymatgen release, calc quality analysis needs to be updated

**Comment by JaGeo** [comment]
You are invited to prepare both PRs. I will merge them

**Comment by JaGeo** [comment]
Realated question: can you keepnthe pymatgen PR backward compatible?

**Comment by naik-aakash** [comment]
I notice, there was also overshadowed argument "type" in earlier implementation (now changed to fp_type), and also keeping backward compatibility is not possible and I did not think ahead when we wrote the code for DOS fingerprints and had added `tanimoto` arg as `bool`.

**Comment by naik-aakash** [comment]
> Realated question: can you keepnthe pymatgen PR backward compatible?

I notice, there was also overshadowed argument "type" in earlier implementation (now changed to fp_type), and also keeping backward compatibility is not possible and I did not think ahead when we wrote the code for DOS fingerprints and had added `tanimoto` arg as `bool`.

**Comment by naik-aakash** [comment]
> You are invited to prepare both PRs. I will merge them

Yes, will do, but as mentioned, will wait for newer pymatgen release first 😃
