### ISSUE TITLE
ICOHPLIST.lobster format changed in  lobster 5.1.1

### ISSUE THREAD

**Issue by yumaoDFT** [JaGeo/LobsterPy#336]
ICOHPLIST.lobster format changed in lobster 5.1.1, which pops out a ValueError when parsing with Analysis.
![Snipaste_2024-10-02_13-53-39](https://github.com/user-attachments/assets/81da82c5-530f-45b7-826b-5ecc8bfed986)

I checked the ICOHPLIST.lobster; it now has spin 1 and spin 2 values on the same row. Previously, spin 1 and spin 2 are written in different rows.
![Snipaste_2024-10-02_13-54-51](https://github.com/user-attachments/assets/d1be926e-06bf-4e1e-b2a3-558fe2815347)

**Comment by JaGeo** [comment]
Thank you for reporting this. We are working on this. We currently have a PR open in pymatgen and hope to close it in the next days.

See https://github.com/materialsproject/pymatgen/pull/4065

**Comment by naik-aakash** [comment]
Hi @yumaoDFT, the changes necessary in the code to make it work with new versions of LOBSTER are already in place. 

Maybe a new release of Pymatgen can take a while. In case you need to be able to use it urgently, uninstall the Pymatgen version you have and then please install the specific branch using the following command: 

`pip install git+https://github.com/naik-aakash/pymatgen.git@lobster_parsers_update`

**Comment by yumaoDFT** [comment]
Thank you very much!

**Comment by JaGeo** [comment]
To close this, we should update as soon as a new pymatgen version is out
