### ISSUE TITLE
lobster workflow failed due to NBANDS change

### ISSUE THREAD

**Issue by yuan-gist** [JaGeo/LobsterPy#348]
Hi, I am trying to run atomate2 Lobster workflow for the MgO example, and noticed a failure of the first `static` run:
`Within a static run, the wave function is pre-converged with symmetry switched on.`

For this `static` run, I first got a warning from VASP, 

> The number of bands has been changed from the values supplied in        |
> |     the INCAR file. This is a result of running the parallel version.       |
> |     The orbitals not found in the WAVECAR file will be initialized with     |
> |     random numbers, which is usually adequate. For correlated               |
> |     calculations, however, you should redo the groundstate calculation.     |
> |     I found NBANDS = 8. Now, NBANDS = 64.

After a few electronic steps, Custodian terminates the job and throws an error:

> ERROR:custodian.custodian:VaspErrorHandler
> ERROR:custodian.custodian:Unrecoverable error for handler: <custodian.vasp.handlers.VaspErrorHandler object at 0x146c7fd89360>
> Traceback (most recent call last):
>   File "~/anaconda3/envs/lobster/lib/python3.10/site-packages/fireworks/core/rocket.py", line 262, in run
>     m_action = t.run_task(my_spec)
>   File "~/anaconda3/envs/lobster/lib/python3.10/site-packages/jobflow/managers/fireworks.py", line 177, in run_task
>     response = job.run(store=store)
>   File "~/anaconda3/envs/lobster/lib/python3.10/site-packages/jobflow/core/job.py", line 600, in run
>     response = function(*self.function_args, **self.function_kwargs)
>   File "~/anaconda3/envs/lobster/lib/python3.10/site-packages/atomate2/vasp/jobs/base.py", line 228, in make
>     run_vasp(**self.run_vasp_kwargs)
>   File "~/anaconda3/envs/lobster/lib/python3.10/site-packages/atomate2/vasp/run.py", line 161, in run_vasp
>     custodian_manager.run()
>   File "~/anaconda3/envs/lobster/lib/python3.10/site-packages/custodian/custodian.py", line 385, in run
>     self._run_job(job_n, job)
>   File "~/anaconda3/envs/lobster/lib/python3.10/site-packages/custodian/custodian.py", line 529, in _run_job
>     raise NonRecoverableError(msg, raises=True, handler=corr["handler"])
> custodian.custodian.NonRecoverableError: Unrecoverable error for handler: <custodian.vasp.handlers.VaspErrorHandler object at 0x146c7fd89360>
> INFO:rocket.launcher:Rocket finished

I checked the custodian.json file, and found:
> "corrections": [
>             {
>                 "errors": [
>                     "auto_nbands"
>                 ],

My question is, why in the automatically generated INCAR for this `static` run, `NBANDS` is set to `8`? which equals to the number of electrons for the MgO example. In previous relaxation runs, NBANDS is automatically set to 64. This issue is related to the `2024.10.14 Change Log` of Custodian (https://materialsproject.github.io/custodian/changelog.html). 

Thanks in advance!

**Comment by JaGeo** [comment]
Thanks for reporting this. We will look into it.

**Comment by JaGeo** [comment]
But could you maybe copy this over to custodian and post your assumption on the issue there? This would help. Thanks!

**Comment by yuan-gist** [comment]
Thanks Janine! As I tested, the workflow works fine for Custodian [v2024.4.18](https://github.com/materialsproject/custodian/releases/tag/v2024.4.18)

**Comment by JaGeo** [comment]
Great!
