### ISSUE TITLE
Add options for DOSCAR.lobster plotting

### ISSUE THREAD

**Issue by JaGeo** [JaGeo/LobsterPy#41]
There should be a command-line option to easily plot projected DOS from Lobster.

**Comment by JaGeo** [comment]
This would be great!  😃

Is it built on the pymatgen implementations or did you choose a different approach?

**Comment by davSchnieders** [comment]
It is a very naive implementation from scratch. It simply reads the contents of a DOSCAR.lobster file and stores them in a dict for further usage. The class implements a plotting function that uses matplotlib to plot the DOS. It exposes a CLI that allows to flexibly choose which states to plot, e.g., "total_dos Na.1.3s" would plot the DOS of the 3s orbital of atom Na1 next to the total DOS (within the same DOS plot). Wildcards are allowed as well, for example "Na.*.3p*" would plot all 3p DOS of all Na atoms.

**Comment by JaGeo** [comment]
Done! 

@davSchnieders , if you have feedback, let us know!
